import pandas as pd
df = pd.read_csv('data/naver_headline_news_Culture_20260604.csv')
print(df.head())

df_temp = pd.read_csv('data/naver_news_IT_Science_20260604.csv')
print(df_temp.head())
df = pd.concat([df,df_temp], ignore_index=True)
df_temp = pd.read_csv('data/naver_news_section.csv')
print(df_temp.head())
df = pd.concat([df,df_temp], ignore_index=True)
df_temp = pd.read_csv('data/naver_news_section_p.csv')
print(df_temp.head())
df = pd.concat([df,df_temp], ignore_index=True)
df_temp = pd.read_csv('data/naver_news_section_social.csv')
print(df_temp.head())
df = pd.concat([df,df_temp], ignore_index=True)
df_temp = pd.read_csv('data/naver_news_world_20260604.csv')
print(df_temp.head())
df = pd.concat([df,df_temp], ignore_index=True)
df_temp = pd.read_csv('data/naver_headline_news_20260605.csv')
print(df_temp.head())
df = pd.concat([df,df_temp], ignore_index=True)
df = df.drop_duplicates()
print(df.category.value_counts())
print(df.isnull().sum())
df.info()
df.to_csv('./data/news_titles.csv', index=False)
